In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('Advertising.csv')

In [15]:
X = df.drop('sales',axis=1)

In [16]:
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [17]:
y = df['sales']

In [18]:
from sklearn.preprocessing import PolynomialFeatures

In [19]:
Polynomial_convertor = PolynomialFeatures(degree=3, include_bias=False)

In [20]:
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [21]:
poly_features = Polynomial_convertor.fit_transform(X)

In [22]:
poly_features.shape

(200, 19)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split( poly_features, y, test_size=0.3, random_state=101)

In [25]:
X_train

array([[1.93200000e+02, 1.84000000e+01, 6.57000000e+01, ...,
        2.22433920e+04, 7.94234160e+04, 2.83593393e+05],
       [2.87600000e+02, 4.30000000e+01, 7.18000000e+01, ...,
        1.32758200e+05, 2.21675320e+05, 3.70146232e+05],
       [8.02000000e+01, 0.00000000e+00, 9.20000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 7.78688000e+02],
       ...,
       [2.39800000e+02, 4.10000000e+00, 3.69000000e+01, ...,
        6.20289000e+02, 5.58260100e+03, 5.02434090e+04],
       [2.14700000e+02, 2.40000000e+01, 4.00000000e+00, ...,
        2.30400000e+03, 3.84000000e+02, 6.40000000e+01],
       [1.63300000e+02, 3.16000000e+01, 5.29000000e+01, ...,
        5.28238240e+04, 8.84297560e+04, 1.48035889e+05]], shape=(140, 19))

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scalar = StandardScaler()

In [28]:
scalar.fit(X_train)

StandardScaler()

In [29]:
X_train = scalar.transform(X_train) #scaling down to very less cofficience

In [30]:
X_test = scalar.transform(X_test)

In [31]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]], shape=(140, 19))

# Implementing the rigde model (L2 regression)

In [32]:
from sklearn.linear_model import Ridge

In [33]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(
 |      alpha=1.0,
 |      *,
 |      fit_intercept=True,
 |      copy_X=True,
 |      max_iter=None,
 |      tol=0.0001,
 |      solver='auto',
 |      positive=False,
 |      random_state=None
 |  )
 |
 |  Linear least squares with l2 regularization.
 |
 |  Minimizes the objective function::
 |
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Constant that multiplies the L2 term, controlling regularization
 |      strength. `alpha` must be a non-negative float i.e. in `[0, inf)`.
 |
 |      When `alpha = 0`, the objective is equivalent to ordinary least
 |      squares, solved by the :class:`LinearRegression` object. For numerical
 |      reasons, using `alpha = 0` with the `Ridge` object is not advised.
 |      Instead, you should use the :class:`LinearRegression` object.
 |
 |      If an array is passed, penalties are assumed to be specific to the
 |      targets. Hence they must correspond in number.
 |
 |  fit_intercept : bool, default=True
 |      Whether to fit the intercept for this model. If set
 |      to false, no intercept will be used in calculations
 |      (i.e. ``X`` and ``y`` are expected to be centered).
 |
 |  copy_X : bool, default=True
 |      If True, X will be copied; else, it may be overwritten.
 |
 |  max_iter : int, default=None
 |      Maximum number of iterations for conjugate gradient solver.
 |      For 'sparse_cg' and 'lsqr' solvers, the default value is determined
 |      by scipy.sparse.linalg. For 'sag' solver, the default value is 1000.
 |      For 'lbfgs' solver, the default value is 15000.
 |
 |  tol : float, default=1e-4
 |      The precision of the solution (`coef_`) is determined by `tol` which
 |      specifies a different convergence criterion for each solver:
 |
 |      - 'svd': `tol` has no impact.
 |
 |      - 'cholesky': `tol` has no impact.
 |
 |      - 'sparse_cg': norm of residuals smaller than `tol`.
 |
 |      - 'lsqr': `tol` is set as atol and btol of scipy.sparse.linalg.lsqr,
 |        which control the norm of the residual vector in terms of the norms of
 |        matrix and coefficients.
 |
 |      - 'sag' and 'saga': relative change of coef smaller than `tol`.
 |
 |      - 'lbfgs': maximum of the absolute (projected) gradient=max|residuals|
 |        smaller than `tol`.
 |
 |      .. versionchanged:: 1.2
 |         Default value changed from 1e-3 to 1e-4 for consistency with other linear
 |         models.
 |
 |  solver : {'auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg',             'sag', 'saga', 'lbfgs'}, default='auto'
 |      Solver to use in the computational routines:
 |
 |      - 'auto' chooses the solver automatically based on the type of data.
 |
 |      - 'svd' uses a Singular Value Decomposition of X to compute the Ridge
 |        coefficients. It is the most stable solver, in particular more stable
 |        for singular matrices than 'cholesky' at the cost of being slower.
 |
 |      - 'cholesky' uses the standard scipy.linalg.solve function to
 |        obtain a closed-form solution.
 |
 |      - 'sparse_cg' uses the conjugate gradient solver as found in
 |        scipy.sparse.linalg.cg. As an iterative algorithm, this solver is
 |        more appropriate than 'cholesky' for large-scale data
 |        (possibility to set `tol` and `max_iter`).
 |
 |      - 'lsqr' uses the dedicated regularized least-squares routine
 |        scipy.sparse.linalg.lsqr. It is the fastest and uses an iterative
 |        procedure.
 |
 |      - 'sag' uses a Stochastic Average Gradient descent, and 'saga' uses
 |        its improved, unbiased version named SAGA. Both methods also use an
 |        iterative procedure, and are often faster than other solvers when
 |        both n_samples and n_features are large. Note that 'sag' and
 |        'saga' fast convergence is only guaranteed on features with
 |        approximately the same scale. You can preprocess the data with a
 |        scaler from sklearn.preprocessing.
 |
 |      - 'lbfgs' uses L-BFGS-B algorithm implemented in
 |        `scipy.optimize.minimize`. It can be used only when `positive`
 |        is True.
 |
 |      All solvers except 'svd' support both dense and sparse data. However, only
 |      'lsqr', 'sag', 'sparse_cg', and 'lbfgs' support sparse input when
 |      `fit_intercept` is True.
 |
 |      .. versionadded:: 0.17
 |         Stochastic Average Gradient descent solver.
 |      .. versionadded:: 0.19
 |         SAGA solver.
 |
 |  positive : bool, default=False
 |      When set to ``True``, forces the coefficients to be positive.
 |      Only 'lbfgs' solver is supported in this case.
 |
 |  random_state : int, RandomState instance, default=None
 |      Used when ``solver`` == 'sag' or 'saga' to shuffle the data.
 |      See :term:`Glossary <random_state>` for details.
 |
 |      .. versionadded:: 0.17
 |         `random_state` to support Stochastic Average Gradient.
 |
 |  Attributes
 |  ----------
 |  coef_ : ndarray of shape (n_features,) or (n_targets, n_features)
 |      Weight vector(s).
 |
 |  intercept_ : float or ndarray of shape (n_targets,)
 |      Independent term in decision function. Set to 0.0 if
 |      ``fit_intercept = False``.
 |
 |  n_iter_ : None or ndarray of shape (n_targets,)
 |      Actual number of iterations for each target. Available only for
 |      sag and lsqr solvers. Other solvers will return None.
 |
 |      .. versionadded:: 0.17
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  solver_ : str
 |      The solver that was used at fit time by the computational
 |      routines.
 |
 |      .. versionadded:: 1.5
 |
 |  See Also
 |  --------
 |  RidgeClassifier : Ridge classifier.
 |  RidgeCV : Ridge regression with built-in cross validation.
 |  :class:`~sklearn.kernel_ridge.KernelRidge` : Kernel ridge regression
 |      combines ridge regression with the kernel trick.
 |
 |  Notes
 |  -----
 |  Regularization improves the conditioning of the problem and
 |  reduces the variance of the estimates. Larger values specify stronger
 |  regularization. Alpha corresponds to ``1 / (2C)`` in other linear
 |  models such as :class:`~sklearn.linear_model.LogisticRegression` or
 |  :class:`~sklearn.svm.LinearSVC`.
 |
 |  Examples
 |  --------
 |  >>> from sklearn.linear_model import Ridge
 |  >>> import numpy as np
 |  >>> n_samples, n_features = 10, 5
 |  >>> rng = np.random.RandomState(0)
 |  >>> y = rng.randn(n_samples)
 |  >>> X = rng.randn(n_samples, n_features)
 |  >>> clf = Ridge(alpha=1.0)
 |  >>> clf.fit(X, y)
 |  Ridge()
 |
 |  Method resolution order:
 |      Ridge
 |      sklearn.base.MultiOutputMixin
 |      sklearn.base.RegressorMixin
 |      _BaseRidge
 |      sklearn.linear_model._base.LinearModel
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._repr_html.base.ReprHTMLMixin
 |      sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(
 |      self,
 |      alpha=1.0,
 |      *,
 |      fit_intercept=True,
 |      copy_X=True,
 |      max_iter=None,
 |      tol=0.0001,
 |      solver='auto',
 |      positive=False,
 |      random_state=None
 |  )
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __sklearn_tags__(self)
 |
 |  fit(self, X, y, sample_weight=None)
 |      Fit Ridge regression model.
 |
 |      Parameters
 |      ----------
 |      X : {ndarray, sparse matrix} of shape (n_samples, n_features)
 |          Training data.
 |
 |      y : ndarray of shape (n_samples,) or (n_samples, n_targets)
 |          Target values.
 |
 |      sample_weight : float or ndarray of shape (n_samples,), default=None
 |          Individual weights for each sample. If given a float, every sample
 |          will have the same weight.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted estimator.
 |
 |  set_fit_request(
 |      self: sklearn.linear_model._ridge.Ridge,
 |      *,
 |      sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$'
 |  ) -> sklearn.linear_model._ridge.Ridge from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Configure whether metadata should be requested to be passed to the ``fit`` method.
 |
 |              Note that this method is only relevant when this estimator is used as a
 |              sub-estimator within a :term:`meta-estimator` and metadata routing is enabled
 |              with ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |              Please check the :ref:`User Guide <metadata_routing>` on how the routing
 |              mechanism works.
 |
 |              The options for each parameter are:
 |
 |              - ``True``: metadata is requested, and passed to ``fit`` if provided. The request is ignored if metadata is not provided.
 |
 |              - ``False``: metadata is not requested and the meta-estimator will not pass it to ``fit``.
 |
 |              - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |              - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |              The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |              existing request. This allows you to change the request for some
 |              parameters and not others.
 |
 |              .. versionadded:: 1.3
 |
 |              Parameters
 |              ----------
 |              sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |                  Metadata routing for ``sample_weight`` parameter in ``fit``.
 |
 |              Returns
 |              -------
 |              self : object
 |                  The updated object.
 |
 |  set_score_request(
 |      self: sklearn.linear_model._ridge.Ridge,
 |      *,
 |      sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$'
 |  ) -> sklearn.linear_model._ridge.Ridge from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Configure whether metadata should be requested to be passed to the ``score`` method.
 |
 |              Note that this method is only relevant when this estimator is used as a
 |              sub-estimator within a :term:`meta-estimator` and metadata routing is enabled
 |              with ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |              Please check the :ref:`User Guide <metadata_routing>` on how the routing
 |              mechanism works.
 |
 |              The options for each parameter are:
 |
 |              - ``True``: metadata is requested, and passed to ``score`` if provided. The request is ignored if metadata is not provided.
 |
 |              - ``False``: metadata is not requested and the meta-estimator will not pass it to ``score``.
 |
 |              - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |              - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |              The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |              existing request. This allows you to change the request for some
 |              parameters and not others.
 |
 |              .. versionadded:: 1.3
 |
 |              Parameters
 |              ----------
 |              sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |                  Metadata routing for ``sample_weight`` parameter in ``score``.
 |
 |              Returns
 |              -------
 |              self : object
 |                  The updated object.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {}
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.MultiOutputMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.RegressorMixin:
 |
 |  score(self, X, y, sample_weight=None)
 |      Return :ref:`coefficient of determination <r2_score>` on test data.
 |
 |      The coefficient of determination, :math:`R^2`, is defined as
 |      :math:`(1 - \frac{u}{v})`, where :math:`u` is the residual
 |      sum of squares ``((y_true - y_pred)** 2).sum()`` and :math:`v`
 |      is the total sum of squares ``((y_true - y_true.mean()) ** 2).sum()``.
 |      The best possible score is 1.0 and it can be negative (because the
 |      model can be arbitrarily worse). A constant model that always predicts
 |      the expected value of `y`, disregarding the input features, would get
 |      a :math:`R^2` score of 0.0.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Test samples. For some estimators this may be a precomputed
 |          kernel matrix or a list of generic objects instead with shape
 |          ``(n_samples, n_samples_fitted)``, where ``n_samples_fitted``
 |          is the number of samples used in the fitting for the estimator.
 |
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          True values for `X`.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights.
 |
 |      Returns
 |      -------
 |      score : float
 |          :math:`R^2` of ``self.predict(X)`` w.r.t. `y`.
 |
 |      Notes
 |      -----
 |      The :math:`R^2` score used when calling ``score`` on a regressor uses
 |      ``multioutput='uniform_average'`` from version 0.23 to keep consistent
 |      with default value of :func:`~sklearn.metrics.r2_score`.
 |      This influences the ``score`` method of all the multioutput
 |      regressors (except for
 |      :class:`~sklearn.multioutput.MultiOutputRegressor`).
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.linear_model._base.LinearModel:
 |
 |  predict(self, X)
 |      Predict using the linear model.
 |
 |      Parameters
 |      ----------
 |      X : array-like or sparse matrix, shape (n_samples, n_features)
 |          Samples.
 |
 |      Returns
 |      -------
 |      C : array, shape (n_samples,)
 |          Returns predicted values.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |      Helper for pickle.
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  __sklearn_clone__(self)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  get_metadata_routing(self)
 |      Get metadata routing of this object.
 |
 |      Please check :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      Returns
 |      -------
 |      routing : MetadataRequest
 |          A :class:`~sklearn.utils.metadata_routing.MetadataRequest` encapsulating
 |          routing information.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  __init_subclass__(**kwargs)
 |      Set the ``set_{method}_request`` methods.
 |
 |      This uses PEP-487 [1]_ to set the ``set_{method}_request`` methods. It
 |      looks for the information available in the set default values which are
 |      set using ``__metadata_request__*`` class attributes, or inferred
 |      from method signatures.
 |
 |      The ``__metadata_request__*`` class attributes are used when a method
 |      does not explicitly accept a metadata through its arguments or if the
 |      developer would like to specify a request value for those metadata
 |      which are different from the default ``None``.
 |
 |      References
 |      ----------
 |      .. [1] https://www.python.org/dev/peps/pep-0487

In [ ]:
ridge_model = Ridge(alpha=10) #honestly we do not know that alpha is equal to 10

In [35]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [36]:
test_predictions = ridge_model.predict(X_test)

In [37]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [38]:
MAE = mean_absolute_error(y_test, test_predictions)

In [39]:
MAE

0.5774404204714166

In [40]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [41]:
RMSE

np.float64(0.8946386461319648)

In [42]:
from sklearn.linear_model import RidgeCV

In [ ]:
# 1. import RidgeCV
# 2. Choose your alphas, and choose your scoring,
# 3.  Let it do its work. 

ridge_CV_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [60]:
ridge_CV_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [54]:
ridge_CV_model.alpha_

np.float64(0.1)

In [55]:
from sklearn.metrics import get_scorer_names

In [61]:
get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'd2_absolute_error_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_max_error',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'neg_root_mean_squared_log_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'top_k_accuracy',
 'v_measure_score']

In [62]:
test_predictions = ridge_CV_model.predict(X_test)

In [63]:
MAE = mean_absolute_error(y_test, test_predictions)

In [64]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [65]:
MAE

0.42737748843375084

In [ ]:
RMSE #Here by using the Rigde regression, we found out better RMSE and MAE than before.

np.float64(0.6180719926926787)

In [67]:
ridge_CV_model.best_score_

-0.3749223340292961

# LASSO - Least absolute shrinkage and selection operator (L1 regression)

In [71]:
from sklearn.linear_model import LassoCV

In [72]:
LassoCV

sklearn.linear_model._coordinate_descent.LassoCV

In [81]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5) #here we created the model

In [82]:
lasso_cv_model.fit(X_train, y_train)

d:\Programs\Github\data-science-concepts\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(

LassoCV(cv=5, eps=0.1, n_alphas=100)

In [83]:
lasso_cv_model.alpha_

np.float64(0.4943070909225831)

In [85]:
test_predictions = lasso_cv_model.predict(X_test)

In [86]:
MAE = mean_absolute_error(y_test, test_predictions)

In [87]:
RMSE =np.sqrt(mean_squared_error(y_test, test_predictions))

In [88]:
MAE

0.6541723161252868

In [ ]:
lasso_cv_model.coef_ #lasso is considering only two features

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

# Elastic Net :  L1 and L2 Regularization