In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df = pd.read_csv('Advertising.csv')

In [45]:
X = df.drop('sales',axis=1)

In [46]:
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [47]:
y = df['sales']

In [48]:
from sklearn.preprocessing import PolynomialFeatures

In [49]:
Polynomial_convertor = PolynomialFeatures(degree=3, include_bias=False)

In [50]:
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [51]:
poly_features = Polynomial_convertor.fit_transform(X)

In [52]:
poly_features.shape

(200, 19)

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split( poly_features, y, test_size=0.3, random_state=101)

In [55]:
X_train

array([[1.93200000e+02, 1.84000000e+01, 6.57000000e+01, ...,
        2.22433920e+04, 7.94234160e+04, 2.83593393e+05],
       [2.87600000e+02, 4.30000000e+01, 7.18000000e+01, ...,
        1.32758200e+05, 2.21675320e+05, 3.70146232e+05],
       [8.02000000e+01, 0.00000000e+00, 9.20000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 7.78688000e+02],
       ...,
       [2.39800000e+02, 4.10000000e+00, 3.69000000e+01, ...,
        6.20289000e+02, 5.58260100e+03, 5.02434090e+04],
       [2.14700000e+02, 2.40000000e+01, 4.00000000e+00, ...,
        2.30400000e+03, 3.84000000e+02, 6.40000000e+01],
       [1.63300000e+02, 3.16000000e+01, 5.29000000e+01, ...,
        5.28238240e+04, 8.84297560e+04, 1.48035889e+05]], shape=(140, 19))

In [56]:
from sklearn.preprocessing import StandardScaler

In [57]:
scalar = StandardScaler()

In [58]:
scalar.fit(X_train)

StandardScaler()

In [ ]:
X_train = scalar.transform(X_train) #scaling down to very less cofficience

In [60]:
X_test = scalar.transform(X_test)

In [61]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]], shape=(140, 19))