In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('./Ames_NO_Missing_Data.csv')
df.isnull().sum()

MS SubClass       0
MS Zoning         0
Lot Frontage      0
Lot Area          0
Street            0
                 ..
Mo Sold           0
Yr Sold           0
Sale Type         0
Sale Condition    0
SalePrice         0
Length: 76, dtype: int64

In [7]:
df['MS SubClass'] = df['MS SubClass'].apply(str)

In [9]:
direction = pd.Series(['Up', 'Up', 'Down'])
direction

0      Up
1      Up
2    Down
dtype: object

In [11]:
pd.get_dummies(direction, drop_first=True)

      Up
0   True
1   True
2  False

In [13]:
df.select_dtypes(include=['object'])

,MS SubClass,MS Zoning,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,...,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Sale Type,Sale Condition
0,20,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,TA,Typ,Gd,Attchd,Fin,TA,TA,P,WD,Normal
1,20,RH,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,...,TA,Typ,NaN,Attchd,Unf,TA,TA,Y,WD,Normal
2,20,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Gd,Typ,NaN,Attchd,Unf,TA,TA,Y,WD,Normal
3,20,RL,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Ex,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal
4,60,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,TA,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,80,RL,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,Mitchel,Norm,...,TA,Typ,NaN,Detchd,Unf,TA,TA,Y,WD,Normal
2921,20,RL,Pave,IR1,Low,AllPub,Inside,Mod,Mitchel,Norm,...,TA,Typ,NaN,Attchd,Unf,TA,TA,Y,WD,Normal
2922,85,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,...,TA,Typ,NaN,NaN,NaN,NaN,NaN,Y,WD,Normal
2923,20,RL,Pave,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,TA,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal
2924,60,RL,Pave,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,TA,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal

In [15]:
my_object_df = df.select_dtypes(include=['object'])
my_numeric_df = df.select_dtypes(exclude=['object'])

In [14]:
df_objects_dummies = pd.get_dummies(df.select_dtypes(include=['object']), drop_first=True)

In [17]:
df.isnull().sum() < 0

MS SubClass       False
MS Zoning         False
Lot Frontage      False
Lot Area          False
Street            False
                  ...
Mo Sold           False
Yr Sold           False
Sale Type         False
Sale Condition    False
SalePrice         False
Length: 76, dtype: bool

In [18]:
df['MS SubClass'] = df['MS SubClass'].apply(str)

In [20]:
direction = pd.Series(['Up', 'Up', 'Down'])

In [22]:
pd.get_dummies(direction, drop_first=True)

      Up
0   True
1   True
2  False

In [23]:
df.select_dtypes(include=['object']).nunique()

MS SubClass       16
MS Zoning          7
Street             2
Lot Shape          4
Land Contour       4
Utilities          3
Lot Config         5
Land Slope         3
Neighborhood      28
Condition 1        9
Condition 2        8
Bldg Type          5
House Style        8
Roof Style         6
Roof Matl          7
Exterior 1st      16
Exterior 2nd      17
Mas Vnr Type       4
Exter Qual         4
Exter Cond         5
Foundation         6
Bsmt Qual          5
Bsmt Cond          5
Bsmt Exposure      4
BsmtFin Type 1     6
BsmtFin Type 2     6
Heating            6
Heating QC         5
Central Air        2
Electrical         5
Kitchen Qual       5
Functional         8
Fireplace Qu       5
Garage Type        6
Garage Finish      3
Garage Qual        5
Garage Cond        5
Paved Drive        3
Sale Type         10
Sale Condition     6
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 76 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MS SubClass      2925 non-null   object
 1   MS Zoning        2925 non-null   object
 2   Lot Frontage     2925 non-null   float64
 3   Lot Area         2925 non-null   int64
 4   Street           2925 non-null   object
 5   Lot Shape        2925 non-null   object
 6   Land Contour     2925 non-null   object
 7   Utilities        2925 non-null   object
 8   Lot Config       2925 non-null   object
 9   Land Slope       2925 non-null   object
 10  Neighborhood     2925 non-null   object
 11  Condition 1      2925 non-null   object
 12  Condition 2      2925 non-null   object
 13  Bldg Type        2925 non-null   object
 14  House Style      2925 non-null   object
 15  Overall Qual     2925 non-null   int64
 16  Overall Cond     2925 non-null   int64
 17  Year Built       2925 non-null   int64
 18  Year Remod/Add   2925 non-null   int64
 19  Roof Style       2925 non-null   object
 20  Roof Matl        2925 non-null   object
 21  Exterior 1st     2925 non-null   object
 22  Exterior 2nd     2925 non-null   object
 23  Mas Vnr Type     1152 non-null   object
 24  Mas Vnr Area     2925 non-null   float64
 25  Exter Qual       2925 non-null   object
 26  Exter Cond       2925 non-null   object
 27  Foundation       2925 non-null   object
 28  Bsmt Qual        2845 non-null   object
 29  Bsmt Cond        2845 non-null   object
 30  Bsmt Exposure    2842 non-null   object
 31  BsmtFin Type 1   2845 non-null   object
 32  BsmtFin SF 1     2925 non-null   float64
 33  BsmtFin Type 2   2844 non-null   object
 34  BsmtFin SF 2     2925 non-null   float64
 35  Bsmt Unf SF      2925 non-null   float64
 36  Total Bsmt SF    2925 non-null   float64
 37  Heating          2925 non-null   object
 38  Heating QC       2925 non-null   object
 39  Central Air      2925 non-null   object
 40  Electrical       2925 non-null   object
 41  1st Flr SF       2925 non-null   int64
 42  2nd Flr SF       2925 non-null   int64
 43  Low Qual Fin SF  2925 non-null   int64
 44  Gr Liv Area      2925 non-null   int64
 45  Bsmt Full Bath   2925 non-null   float64
 46  Bsmt Half Bath   2925 non-null   float64
 47  Full Bath        2925 non-null   int64
 48  Half Bath        2925 non-null   int64
 49  Bedroom AbvGr    2925 non-null   int64
 50  Kitchen AbvGr    2925 non-null   int64
 51  Kitchen Qual     2925 non-null   object
 52  TotRms AbvGrd    2925 non-null   int64
 53  Functional       2925 non-null   object
 54  Fireplaces       2925 non-null   int64
 55  Fireplace Qu     1505 non-null   object
 56  Garage Type      2768 non-null   object
 57  Garage Yr Blt    2925 non-null   float64
 58  Garage Finish    2767 non-null   object
 59  Garage Cars      2925 non-null   float64
 60  Garage Area      2925 non-null   float64
 61  Garage Qual      2767 non-null   object
 62  Garage Cond      2767 non-null   object
 63  Paved Drive      2925 non-null   object
 64  Wood Deck SF     2925 non-null   int64
 65  Open Porch SF    2925 non-null   int64
 66  Enclosed Porch   2925 non-null   int64
 67  3Ssn Porch       2925 non-null   int64
 68  Screen Porch     2925 non-null   int64
 69  Pool Area        2925 non-null   int64
 70  Misc Val         2925 non-null   int64
 71  Mo Sold          2925 non-null   int64
 72  Yr Sold          2925 non-null   int64
 73  Sale Type        2925 non-null   object
 74  Sale Condition   2925 non-null   object
 75  SalePrice        2925 non-null   int64
dtypes: float64(11), int64(25), object(40)
memory usage: 1.7+ MB

In [ ]:
my_object_df = df.select_dtypes(include=['object']) #object type columns
my_numeric_df = df.select_dtypes(exclude=['object']) # numeric type columns

In [27]:
df_objects_dummies = pd.get_dummies(df.select_dtypes(include=['object']), drop_first=True)

In [28]:
df_objects_dummies

,MS SubClass_150,MS SubClass_160,MS SubClass_180,MS SubClass_190,MS SubClass_20,MS SubClass_30,MS SubClass_40,MS SubClass_45,MS SubClass_50,MS SubClass_60,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2921,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2922,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2923,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2924,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False

In [29]:
final_df = pd.concat([my_numeric_df, df_objects_dummies], axis=1)

In [31]:
final_df.corr()['SalePrice'].sort_values()

Exter Qual_TA        -0.591459
Kitchen Qual_TA      -0.527461
Bsmt Qual_TA         -0.453022
Garage Finish_Unf    -0.422363
Garage Type_Detchd   -0.365209
                        ...
Garage Cars           0.648488
Total Bsmt SF         0.660983
Gr Liv Area           0.727279
Overall Qual          0.802637
SalePrice             1.000000
Name: SalePrice, Length: 263, dtype: float64